version: '3'

services:
  app:
    build: 
        context: .
        args:
          ARTIFAKT_COMPOSER_INSTALL_PARAMS: "--no-cache --optimize-autoloader --no-interaction --no-ansi --no-dev"
    image: base-php:latest
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - "data:/data"
    environment:
      PHP_CONF_MEMORY_LIMIT: "-1"
      PHP_CONF_DATE_TIMEZONE: "Europe/Berlin"
      PHP_CONF_MAX_EXECUTION_TIME: 180
      PHP_CONF_OPCACHE_VALIDATE_TIMESTAMP: 1

volumes:
  data:
